### ISSUE TITLE
Footnotes badly reindexed

### ISSUE THREAD

**Issue by PiLa-81** [DistributedProofreaders/guiguts#285] opened 2020-10-12 09:09 UTC
In a text where there are a lot of footnotes, on several pages, take example attached. Here, I have already moved the footnotes after the paragraph, I want to renumber them.

[bug_example.txt](https://github.com/DistributedProofreaders/guiguts/files/5364047/bug_example.txt)  

**To Reproduce**
Open Guiguts.  
Load the file attached.  
Click Tools/Footnote fixup  
Click "First pass", then "reindex".  

The footnote anchors in the second paragraph are numbered 9, 2, 3, 5, 10, 11, 4, 6, 7, 8.
The footnotes themselves are numbered correctly from 2 to 11.   

**Expected behavior**
The footnote anchors of the second paragraph should be in order from 2 to 11. 

**Environment**
* Guiguts version: 1.1.1
* OS and version: Linux Mint 20
* Perl version: This is perl 5, version 30, subversion 0 (v5.30.0) built for x86_64-linux-gnu-thread-multi
* Perl distribution:

**Comment by windymilla** [comment] 2020-10-12 19:37
When I run First Pass, the Footnote Check dialog that pops up has several footnotes highlighted in yellow, which means the program can see more than one anchor pointing to the same footnote. 

It says at the top of the dialog
`Warning: You shouldn't attempt to reindex or auto-move footnotes until you've addressed all warnings displayed here`

The warnings are because you have
```
Here[1] is some text[2]. Because it goes
---Page 2---
onto a second page[1], some anchor numbers[2]
are duplicated.

[Footnote 1: There]

[Footnote 2: Lots of text]

[Footnote 1: Which page]

[Footnote 2: Last note]
```

Perhaps you have moved the footnotes since they came out of the rounds? The only thing you should have done at this stage is to join any footnotes that run across a page boundary, I think. I would have expected the above text to come out of the rounds like this:
```
Here[1] is some text[2]. Because it goes

[Footnote 1: There]

[Footnote 2: Lots of text]
---Page 2---
onto a second page[1], some anchor numbers[2]
are duplicated.

[Footnote 1: Which page]

[Footnote 2: Last note]
```

If I restore it to that state, then Fixup doesn't report any errors and Reindex does what I would expect.

Is that OK? If so, I'll close this issue.

**Comment by PiLa-81** [comment] 2020-10-13 18:52
I followed your advice. It works OK this way.  
You can close the issue.

**Comment by windymilla** [comment] 2020-10-13 19:12
Thanks.

Closing as feature works as intended, and gives a warning about handling all footnote errors before reindexing.

**Closed by windymilla** 2020-10-13 19:12 UTC
Labels: bug
