### ISSUE TITLE
Disable the Threshhold word count for marked up phrase.

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#173] opened 2020-08-05 05:37 UTC
The Threshhold word count for marked up phrase currently defaults to a ridiculously low number of 4 which can be changed but the setting is only retained for the current session.  I always want to see all marked up phrases.

Preference: the default "Threshold word count for marked up phrase" would be disabled entirely.

Alternative 1:  the default "Threshold word count for marked up phrase" could be set to a more reasonable number such as 1,000,000,000 instead of 4.

Alternative 2: The ability to set a personal preference to disable the "Threshold word count for marked up phrase." 

Alternative 3: The ability to set a personal preference for the "Threshold word count for marked up phrase." 

Steps to get this window:
1. Open the Word Frequency menu, Tools-->Word Frequency....
2. Click the "Ital/Bold/SC" button
3. The results appear plus another menu for temporarily setting the "Threshold word count for marked up phrase."

![Capture](https://user-images.githubusercontent.com/17208131/89374709-09c1dc80-d6a1-11ea-9ad0-8a2499019acd.PNG)

**Comment by windymilla** [comment] 2020-08-05 12:07
Duplicate of #112

**Closed by windymilla** 2020-08-05 12:07 UTC
Labels: duplicate, enhancement
