### ISSUE TITLE
Word Frequency frq and len sorts are reversed from the original [correct] sort

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#480] opened 2021-01-21 17:35 UTC
**Describe the solution you'd like**
I'd like the word frequency frq or len sort direction to bring the items of interest to the top.  E.g., the most frequent or longest words should appear at the top as they did in 1.0.25.  The sort has been reversed to bring the most useless items to the top--the least frequent or shortest.

**Describe alternatives you've considered**
A setting for sort direction could be enabled in the preferences.

**Additional context**
Correct sorts:
1.0.25 frq
![Capture 1 0 25](https://user-images.githubusercontent.com/17208131/105388664-ca923400-5bcb-11eb-87fd-9ba716131e70.JPG)

1.0.25 len
![Capture 1 0 25 len](https://user-images.githubusercontent.com/17208131/105388572-a8001b00-5bcb-11eb-9836-bb77091f8091.JPG)

Incorrect (reversed) sorts:
1.2.3 frq
![Capture](https://user-images.githubusercontent.com/17208131/105388728-de3d9a80-5bcb-11eb-8243-370d84b017f0.JPG)

1.2.3 len
![Capture len](https://user-images.githubusercontent.com/17208131/105388765-e72e6c00-5bcb-11eb-964f-4a9e04cb2a16.JPG)

**Comment by windymilla** [comment] 2021-01-21 19:25
Duplicate of #471, fixed by #472

**Comment by windymilla** [comment] 2021-01-21 19:26
Duplicate of #471, fixed by #472

**Closed by windymilla** 2021-01-21 19:26 UTC
Labels: duplicate, enhancement
