### ISSUE TITLE
Footnote Fixup=>Join with previous sometimes fails

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#497] opened 2021-01-29 23:35 UTC
**Describe the bug**
Occasionally the second footnote in a merge is erased instead of merging with the first one.

**To Reproduce**
1. Open Guiguts
2. Open the Tools=>Footnote fixup menu ...
3. Select First Pass
4. Double click on the first pink row. (footnote #12)
5. Select "Join with Previous" (this usually works once)
6. Edit anything in the newly merged footnote.  In this case, I joined the poetry stanza by deleting four rows including the ending `*/` and the beginning `/*`.
7. Double click another pink row such as footnote #25. - **See comment below for clarification of error**
8. The footnote that was #25 and the closing bracket for footnote #24 are removed.

**Expected behavior**
I expected the two footnotes to be merged without losing data.

**Environment**
* Guiguts version: 1.2.4-beta and 1.0.25
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**Additional context**
[hazlitt5.zip](https://github.com/DistributedProofreaders/guiguts/files/5896888/hazlitt5.zip)

I have noticed that if I take the trouble to save the file every time after a merge I do not have this problem.

Editing the previous merged footnote seems to be necessary for this file for this fault to occur.  I don't feel that is always the case but can't reproduce it without editing in either of the two footnoted projects I'm currently working on.

**Comment by windymilla** [comment] 2021-01-30 10:54
At point 7 in the steps to reproduce, it is necessary to Join with Previous for footnote 25.
Also, for me, the footnote doesn't disappear completely, but its text is not moved properly to be part of footnote 24. It just remains after the piece of main body text and has lost its footnote markup.
Also, a save after the merge did not solve the problem for me.

**However, re-running First Pass after any editing of a merged footnote does seem to eliminate the problem**

Since this fault occurs in exactly the same way in 1.0.25 (and maybe before that), the fix will not be targeted for release 1.2.4

**Closed** 2021-02-20 00:57 UTC
Labels: bug
