### ISSUE TITLE
Guiguts switches to the foreground during an Auto Save backup and stays

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#456] opened 2021-01-09 19:40 UTC
**Describe the bug**
I am not a touch typist and need to watch the keyboard.  When I am typing in another program such as Slack and Guiguts does an autosave it moves to the foreground and kicks Slack to the background.  The last five lines were typed in Guiguts.

This behavior would also be an annoyance to a touch typist since they would also need to switch back to the other program.

**To Reproduce**
1. Open Guiguts
2. Make certain Preferences=>Backup=>Enable Auto Save is set.
3. Make a change in the open document
4. Switch to another program such as Slack, the DP forums, or Notepad++ and begin typing.
5. When the Auto Save interval elapses after the change in step 3 GuiGuts will switch to the foreground and further characters intended for the other program will be entered into the open Guiguts document.

**Expected behavior**
I expect GuiGuts to stay in the background for intercepting keyboard input until the user calls it back to the foreground, such as an alt-tab, by clicking on the GuiGuts icon on the taskbar, or by clicking on the GUI if visible, etc.

**Environment**
* Guiguts version: 1.2.1
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**Additional context**
I could turn Auto Save off but don't want to lose my work.
I could hit Save before switching programs but I do not wish to rely on remembering to do so.  I feel that is one of the purposes of Auto Save.

**Comment by windymilla** [comment] 2021-01-09 19:49
Thanks. To the best of your knowledge is Guiguts behaving as it always has
done? Or do you think it is a new bug? I'm not aware of having edited that
area, but it's possible something inadvertently affected Guiguts grabbing
the keyboard focus.

**Comment by okrick** [comment] 2021-01-09 19:59
This is an old bug.  As far as I recall Guiguts always grabs the keyboard focus.

**Comment by windymilla** [comment] 2021-01-09 22:27
Thanks. I'll look into it in due course.

**Comment by windymilla** [comment] 2021-02-16 21:34
I cannot reproduce this at all. I set the save interval to 1 minute, made a change and waited, and sure enough it save the file. Then I made a second change and switched to typing into Slack. After 1 minute, the GG icon in the Windows taskbar started flashing (which means something has happened) but it did not grab focus. I'm using Windows 10 Pro.

@okrick, can you think of anything else that might be different or affecting it? Otherwise, I'll have to close this for now.

**Comment by okrick** [comment] 2021-02-16 21:48
Odd. It seems to have quit doing that annoying behavior.  At least in 1.2.4 it no longer grabs focus.

The only thing I can think of is one of the upgrades along the way to 1.2.4.  But I don't recall when it quit.

I'm fine with closing this.

**Comment by windymilla** [comment] 2021-02-16 21:56
I certainly don't recall making that change deliberately, but I have made a
few changes to the way autosave worked, so maybe one of those did it.

**Comment by windymilla** [comment] 2021-02-16 21:57
No longer an issue in 1.2.4

**Closed by windymilla** 2021-02-16 21:57 UTC
Labels: bug
