### ISSUE TITLE
Add other in-line mark ups to the marked up phrase check

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#174] opened 2020-08-05 05:53 UTC
Currently the marked up phrase check only looks for `<b></b>`,  `<i></i>`,  and `<sc></sc>` in-line markups.  I'd like the check to include  `<f></f>`,  `<g></g>`,  `<em></em>`,  `<cite></cite>`,  and `<u></u>` as a minimum.  It is a nuisance to correct the markup only to have the phrase disappear from the listing the next time the check is run.

The steps to initiate this check are:
1. Open Tools-->Word Frequency....
2. Click the Ital/Bold/SC button.

This can easily be done by adding these to the list in the WordFrequency.pm line 814.

**Comment by windymilla** [comment] 2020-08-05 12:11
Duplicate of #111

**Closed by windymilla** 2020-08-05 12:11 UTC
Labels: duplicate, enhancement
