### ISSUE TITLE
Just as for WF, both Spell Query and Spell Check do not consider as part of a word, composed characters that can't be normalised

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#1122] opened 2023-03-01 13:34 UTC
**Describe the bug**
I'm seeing in both SQ and SC exactly the same problem with a composed character as I reported in Word Frequency, namely that the letter 'i' plus a 'reverse comma above' (which can't be normalised) is not recognised as part of a word. I note you may already be dealing with this sort of problem as part of issue #1118?

Bookloupe>Query word exhibits similar behaviour too. See comment below.

**To Reproduce**
1. Open Guiguts with 
[SQ-error-example.txt](https://github.com/DistributedProofreaders/guiguts/files/10861306/SQ-error-example.txt)
2. Open the Tools>Spell Check menu 
3. See that the word 'Pi̔ngs' is not treated as a whole word. As a BTW, neither is the word 'Ta̔i' but it appears that happens to be broken in to parts that are 'words' recognised by Spell Check.
4. Repeat steps 2) & 3) but instead using Tools>Spell Query

**Expected behavior**
As for your fix to Word Frequency

**Environment**
* Guiguts version: 1.5.3-test3
* OS and version: Windows 10
* Perl version: 
* Perl distribution: 

**Screenshots**

**Additional context**
The following comments are not context as such, but reflections/questions on and about the behaviour of Spell Query (SQ).
1. I'm surprised that Spell Check (SC) can process text that has not been saved to a file but that Spell Query requires the text to be saved to a file first.
2. I may have encountered a GG error when I first ran SQ without first saving the text to a file. I have not been able to reproduce the error but it happened while you have the "No Filename" popup open telling you that "File has not been saved." There was also a blue popup open saying "Working...\nSpell Query\nPLease wait". The error message I saw said "12:43:17: Use of uninitialized value $msg in concatenation (.) or string at C:/Users/nqgc/Desktop/DP/Tools/guiguts-1.5.3-test3/lib/Guiguts/Utilities.pm line 774."
3. I thought that SQ used a more comprehensive English dictionary so was surprised to see the word "unimportance" flagged while SC does not flag it. This is a minor point and I may have misunderstood the dictionary issues.

**Comment by windymilla** [comment] 2023-03-01 13:52
Yes, #1118 is a plan to check the rest of the code for things that are similar to the WF issue. Please keep this issue open though, as a specific reminder about Spell Query.

Note that I will probably only do #1118 after 1.5.3 has been released, so it will come in 1.6. There's a concern that it might break something, so I don't want to risk it in a minor update release without the opportunity for more testing.

I may not do anything about Spell Check, partly because I know for certain that you won't find those words in the SC dictionaries. Spell Check scarcely copes with non-Latin1 characters, never mind combining characters, and I don't plan to put much effort into continuing its maintenance.

Regarding your other points:
1. I note your surprise :) - many of the tools require you to save a file. It's not something that will happen in real usage.
2. I've added a separate issue about this bug (#1123) - I can see the bug in the code, although I can't reproduce it
3. I don't know that SQ's dictionary is more comprehensive, but even if it is, that's not to say every word in the SC dictionary is contained in SQ's dictionary - just add it to your global dictionary and you're done.

**Comment by windymilla** [comment] 2023-03-01 14:38
More info on point 2. To reproduce the error, when the "working" dialog and the "File has not been saved" dialog appear, make sure you dismiss the "working" dialog first. The error then occurs when you dismiss the error dialog and the code tries to dismiss the already-dismissed "working" dialog.

**Comment by G4OEU** [comment] 2023-03-05 14:57
Another place where a composed character that can't be normalised causes problems is Bookloupe. Create a nonsense word and add a REVERSE COMMA ABOVE (U+0314, Dec. 788) to a letter near the middle of the word. Run Bookloupe>Query word. The behaviour is similar to the way words are split by SC and SQ.

**Comment by windymilla** [comment] 2023-03-05 15:11
I'm afraid we'll have to live with that. Bookloupe is a separate program with its source stored elsewhere, and is also used by people outside DP and non-GG users, so I can't really fix things in it. I put a couple of patches in GG to adjust the messages that it displays from bookloupe, but the composed character problem bookloupe has can't be fixed by a patch in GG,

**Closed** 2023-03-12 20:40 UTC
Labels: bug
