### ISSUE TITLE
Malformed UTF-8 character: \x9c

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#506] opened 2021-02-06 18:21 UTC
**Describe the bug**
20:04:09: Guiguts 1.2.4-beta: If you have any problems, please include any error messages that appear here with your bug report.
10:11:06: Malformed UTF-8 character: \x9c (unexpected continuation byte 0x9c, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.
10:11:06: Malformed UTF-8 character: \x9c (unexpected continuation byte 0x9c, with no preceding start byte) in subroutine entry at C:/Strawberry/perl/site/lib/Tk.pm line 251.

**To Reproduce**
1. Open Guiguts
2. Click on the end of the word "Non-partisan" in line 19306
3. Press Ctrl-left arrow

**Expected behavior**
I expected the word to be selected without an error message.

**Environment**
* Guiguts version:  1.2.4-beta
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.30.3.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.30.3.1-64bit

**files**
[brass.zip](https://github.com/DistributedProofreaders/guiguts/files/5937391/brass.zip)

**Additional context**
Closing & reopening Guiguts stops this behavior.  I included all bks & the bin.bak in the zip iin the hope that there may be a clue in them.

I was working through the WF hyphenation checks when this happened.

**Comment by windymilla** [comment] 2021-02-06 18:34
Thanks. Can you confirm if this is 1.2.4-beta or the 1.2.4-beta2 that I sent a link for a couple of days ago.

**Comment by windymilla** [comment] 2021-02-06 19:45
For me, it fails in 1.2.4-beta, but my fix in 1.2.4-beta2 seems to make it OK.
To make it go wrong in 1.2.4-beta or previous 1.2 releases, load the file, do Word Freq, Hyphens, then double click Non-partisan in the WF hyphenated word list. The word in the main text will highlight. Click at the end of the word, then Ctrl-left-arrow three times. Error pops on the third key press. 
But, good news(!), fixed in 1.2.4-beta2, I believe, and therefore will be fixed in the new 1.2.4 to be released shortly.

**Comment by okrick** [comment] 2021-02-07 02:10
I thought I installed beta2 but clearly not.  Help Software versions says 1.2.4-beta.  

Sorry.  I'll install it right now before I forget.

Thank you

**Comment by windymilla** [comment] 2021-02-07 19:46
Closing since a duplicate of an already fixed bug

**Closed by windymilla** 2021-02-07 19:46 UTC
Labels: bug
