### ISSUE TITLE
Issues with straight to curly quote conversion 

### ISSUE THREAD

**Issue by G4OEU** [DistributedProofreaders/guiguts#628] opened 2021-03-15 17:12 UTC
**Describe the bug**

1. It failed to convert one of the two single  quotes in the included HTML file;
2. It does not protect quotes within HTML tags. They get converted too. This is unlike PPMSQ which changes them to special characters which need to be converted back to straight quotes. This change in behaviour may be deliberate if UTF-8-style quote characters are now permitted in HTML tags?

**To Reproduce**
1. Open Guiguts with [curly-quotes.html](https://github.com/DistributedProofreaders/guiguts/files/6143081/curly-quotes.zip)
2. Open the Txt>Convert to Curly Quotes...
3. Scroll down to the  line with the `'<p class=“italic”>'` tag and observer first that the straight quotes within the `<p>` tag have ben converted. Then look along the line to the second instance of the word 'here' and note that the first of the two enclosing single quote characters has not been converted.

**Expected behavior**
Obvious in the case of conversion of straight quotes outside of HTML tags. Query whether conversion is deliberate in the case of straight quotes within HTML tags.

**Environment**
* Guiguts version: 1.3_210313
* OS and version:  Windows 10
* Perl version: v5.30.3
* Perl distribution: Strawberry Perl version 1.676, CPAN.pm version 2.28

**Screenshots**

**Additional context**

**Comment by G4OEU** [comment] 2021-03-15 17:56
I think the failure to convert the first single quote is related to the presence of a single quote (an apostrophe) in the <title> ... <title> string. Investigating further.

**Comment by G4OEU** [comment] 2021-03-15 18:29
The failure to convert the first of the two enclosing single quotes is not related to the presence of the apostrophe in the title text. If that is removed and the file converted as above, the problem still occurs.

**Comment by windymilla** [comment] 2021-03-15 19:34
Thanks for testing - at the moment, I don't think any action is necessary for these two points - see below for details.

1. Running this HTML through ppsmq online, it does not convert the first enclosing single quote either. The GG tool uses the same algorithm as ppsmq. The problem is that the first quote could be an apostrophe, e.g. 
'Come over 'ere'.
Because of the apostrophe/single quote confusion, ppsmq (and hence GG) converts single quotes far less well. In the ppsmq instructions, it says to check for the `@` symbol (dubious double quote conversion) and check for the single quotes which will be left unconverted.

2. The tool in Guiguts is only implemented for text files, not the HTML version. That's why I put it in the Txt menu, not in the Tools menu. I should have mentioned that in the "release notes" I gave you - sorry - I've added it in my version so it ends up being correct in the Changelog and manual. The reasons I didn't implement the HTML version: the user should convert before splitting text and HTML version; it is not completely reliable as it does not have an HTML parser so can get confused when a space is left in or a line break occurs (legally) where it doesn't expect one; it leaves behind odd characters in place of single and double quotes used for HTML purposes that the user has to convert back after correcting outstanding straight quotes - this would need at least one extra menu entry to do that job; you can use the online ppwb in the rare case of actually needing to convert an HTML file. If there's a big outcry, I could reconsider that decision.

If you're happy with both of the above, you (or I) could close this issue.

**Comment by G4OEU** [comment] 2021-03-15 20:58
Hi Nigel,

Thanks fof the reply. I'm happy with your response to this report so will
close it.

Quentin

**Closed** 2021-03-15 21:02 UTC
Labels: bug
