### ISSUE TITLE
Poetry stanzas missing closing </p>

### ISSUE THREAD

**Issue by okrick** [DistributedProofreaders/guiguts#752] opened 2021-05-05 02:23 UTC
**Describe the bug**

```
<p>Power and beauty and knowledge,—
Pan, Aphrodite, or Hermes,—
Whom shall we life-loving mortals
<span style="margin-left: 1em;">Serve and be happy?</span><br />
 
<p>Lo now, your garlanded altars,                                          <span class="linenum">5</span>
Are they not goodly with flowers?
Have ye not honour and pleasure
<span style="margin-left: 1em;">In lovely Lesbos?</span><br />
```

**To Reproduce**
1. Open Guiguts
2. Open the HTML Generator menu ...
3. Selections were Keep UTF-8 Chars., Keep Latin-1 Chars., Short FN Anchors, and Find and Format Poetry Line Numbers
4. See the above output. The stanzas had opening `<p>` elements but no `</p>` elements.

**Expected behavior**
I expect there to be one closing `</p>` for every opening `<p>`.

**Environment**
* Guiguts version:  1.3.0
* OS and version: Windows 10 Home 20H2
* Perl version: Strawberry Perl (64-bit) 5.32.1.1-64bit
* Perl distribution: Strawberry Perl (64-bit) 5.32.1.1-64bit

**Screenshots**
![Capture](https://user-images.githubusercontent.com/17208131/117090736-003bd280-ad0e-11eb-92d4-de74053f1c4c.JPG)

**Additional context**
The original text was an ASCII PG text file updated to UTF-8.

**Comment by windymilla** [comment] 2021-05-05 07:17
Please could you supply the input file so I can reproduce it. I can't reproduce the problem from the output. Thanks.

**Comment by okrick** [comment] 2021-05-05 14:38
Sorry, I forgot.

[12389-h-htmlbak.txt](https://github.com/DistributedProofreaders/guiguts/files/6427909/12389-h-htmlbak.txt)

**Comment by okrick** [comment] 2021-05-05 15:37
By the way, take your time.  I decided not to do an HTML version for this one.  I was so focused on clearing the W3C Validation issues that I failed to notice the poem lines were not ended in <br />.  Ebookmaker would do a better job of producing an HTML out of the text version.

**Comment by okrick** [comment] 2021-05-05 15:48
Oops, I didn't mean to imply that Guiguts does a bad job on HTML conversion.  I mean that this text file which lacks the usual formatting markups would take a lot of TLC to get it in a format that Guiguts could turn into a presentable HTML file. And I doubt it would be a huge improvement over the ebookmaker generated HTML at PG.

**Comment by windymilla** [comment] 2021-05-05 19:59
Thanks Rick. As you discovered, the file isn't marked up for HTML conversion. If the poem is surrounded with /P...P/ markup, it converts successfully. The combination of indented lines but no markup means Guiguts doesn't work out where to put the closing paragraph markup. I'm not going to fix this as it's not going to happen in a correctly marked up file. Worth checking though, thanks.

**Closed by windymilla** 2021-05-05 19:59 UTC
Labels: bug
