### ISSUE TITLE
Allow ESC to interrupt an endless loop caused by an invalid regex

### ISSUE THREAD

**Issue by charliehoward4dp** [DistributedProofreaders/guiguts#369] opened 2020-12-05 06:58 UTC
Doing a regex search for something like

/*\n

causes GG to loop endlessly.  It's due to a careless user error, but the only way out right now is to force-close GG, losing any unsaved work. It would be nice if GG monitored the ESC key and got out of the endless loop if the key is pressed.

**Comment by windymilla** [comment] 2021-03-02 16:34
Does this still go wrong in the version you have? I can't reproduce it.

**Comment by charliehoward4dp** [comment] 2021-03-02 17:33
Yes it still can go into an unterruptible state, where the ‘interrupt’ button does not appear. I don’t know exactly how to make it happen but will let you know the conditions the next time it happens.

**Comment by charliehoward4dp** [comment] 2021-03-04 01:15
I haven't been able to reproduce this since you asked about it, but it occurs unpredictably, and when it's happened in the past, I didn't write down the regex (and couldn't copy/paste it into my 'notes' file, since GG was non-responsive). 

If it happens again, I'll write down the regex and put it in this or another report.

**Comment by windymilla** [comment] 2021-03-04 09:14
It's possible that it's been fixed by one of these: #329, #517, #533
Even if they don't describe the visible problem exactly, it might be that the code fix also fixed your problem.
Do you recall if it is when you press the Search button, or Replace, or R&S, or Replace All?

**Comment by windymilla** [comment] 2021-03-06 15:04
Closing, since may have been fixed - re-open or add new issue if it recurs.

**Closed by windymilla** 2021-03-06 15:04 UTC
Labels: enhancement
