### ISSUE TITLE
Discard All Similar Queries error 

### ISSUE THREAD

**Issue by windymilla** [DistributedProofreaders/guiguts#795] opened 2021-07-21 20:50 UTC
**Describe the bug**
The new feature to discard all similar queries by using Ctrl+Shift+Mouse-3 can cause a "bad text index" error

**To Reproduce**
1. start GG and open "t12-bl1.txt" in [gg3.2.2pre1-but.zip](https://github.com/DistributedProofreaders/guiguts/files/6858753/gg3.2.2pre1-but.zip)
2. run Bookloupe
3. hide all options
4. unhide "missing paragraph break"
5. click on the first item and then right-click to remove it.  This will work without error.
6. close GG
7. start GG again and open the same "t12-bl1.txt"
8. run Bookloupe
9. hide all options
10. unhide "no punctuation at paragraph end"
11. click on the first item and then shift+ctrl+right-click to remove all of them.
12. unhide "missing paragraph break", as you had done in step 4.
13. click on the first item and then right-click to remove it.  Unlike 5, you should get this error:
```
15:21:44: Guiguts 1.3.2-pre1: If you have any problems, please include any error messages that appear here with your bug report.
15:23:13: Tk::Error: bad text index "" at C:/Strawberry/perl/site/lib/Tk.pm line 251.
 Tk callback for .frame.linenumbertext.frame.textunicode
 <<view>>
 (command bound to event)
```

**Comment by windymilla** [comment] 2021-07-24 14:00
I'm sorry - I've tried following this exactly, and it doesn't give me an error. Can you try it again please @charliehoward4dp

It looks like the fault happens after removing an error when it tries to <<view>> the next error. Although I could probably stop the error happening by making the <<view>> action check the text index it is trying to jump to, that would just be masking the issue, and GG wouldn't view the next error correctly. So, I'd like to work out what is happening that causes the issue - probably some interaction between bookloupe view options and the removal of errors. 

Thanks

**Comment by charliehoward4dp** [comment] 2021-07-24 17:20
It is not failing for me now, either. I'll try some more variations and comment afterwards.

**Comment by charliehoward4dp** [comment] 2021-07-24 17:47
Have tried other combinations and have not been able to make it fail. Hopefully, it was just a transient glitch on my system.

**Comment by windymilla** [comment] 2021-07-25 13:08
I'll leave this open a bit longer in case the problem re-appears

**Comment by charliehoward4dp** [comment] 2021-07-25 19:57
Good plan, as it did happen again just now, in a different project. Once it happens, it happens again each time an attempt is made to examine or delete an item in the Bookloupe report. Unfortunately, it is not easy to reproduce, so I can't even supply another example.  In the original report, it was reproducible (to me) even after closing and restarting GG (although not reproducible several days later). Today, it did not occur once GG had been restarted. A significant difference is that, today, I did not use Shift+Ctrl+right-click, but was just right-clicking items in the list one at a time. There was a correction made along the way (deleting an extraneous straight double-quote). The error occurred shortly after that, but not immediately afterwards.

**Comment by charliehoward4dp** [comment] 2021-07-28 19:53
With the updated ErrorCheck.pm installed, this issue did not occur. Since it was sporadic, I think it will need further testing before we can confirm the issue has been resolved.

**Closed** 2021-07-29 23:41 UTC
Labels: bug
